version: 2.1

orbs:
  github-wiki: sjawhar/github-wiki@dev:0.3.0

workflows:
  deploy-wiki:
    jobs:
      - github-wiki/build-and-deploy:
          commit-user-email: circleci+orb-github-wiki@thecybermonk.com
          ssh-key-fingerprint: 8a:eb:2e:06:ba:62:78:16:83:22:13:01:6e:ce:8f:8b
          deploy-branch-filter: master
