version: 2.1

orbs:
  github-wiki: sjawhar/github-wiki@0.2.1

workflows:
  deploy-wiki:
    jobs:
      - github-wiki/build-and-push:
          push-wiki-repo: false
          filters:
            branches:
              ignore: master
      - github-wiki/build-and-push:
          commit-user-email: circleci+orb-github-wiki@thecybermonk.com
          ssh-key-fingerprint: 8a:eb:2e:06:ba:62:78:16:83:22:13:01:6e:ce:8f:8b
          filters:
            branches:
              only: master
