version: 2.1

orbs:
  github-wiki: sjawhar/github-wiki@dev:0.1.3

workflows:
  deploy-wiki:
    jobs:
      - github-wiki/build-and-push:
          commit-user-email: circleci+orb-github-wiki@thecybermonk.com
          filters:
            branches:
              only: master
