version: 2.1
description: Automatically build and push to your GitHub repo's Wiki

executors:
  default:
    description: Single Docker container with bash
    docker:
      - image: circleci/node

commands:
  populate-sidebars:
    description: Populate sidebar files with page header links
    parameters:
      sidebar-placeholder:
        type: string
        description: String in sidebar files to replace with page header links
        default: '{{SIDEBAR_POPULATE}}'
      wiki-folder-path:
        type: string
        description: Path to directory containing wiki files
        default: docs
    steps:
      - run:
          name: Populate sidebars
          command: |
            #!/bin/bash
            set -euf -o pipefail

            SIDEBAR_FILE="__Sidebar.md"
            GENERATE_MATCH="<< parameters.sidebar-placeholder >>"

            cd << parameters.wiki-folder-path >>

            for SIDEBAR_PATH in $(find . \
              -type f -name "${SIDEBAR_FILE}" \
              -exec grep -l "${GENERATE_MATCH}" {} \;
            )
            do
              SIDEBAR_DIR="$(dirname ${SIDEBAR_PATH})"
              pushd "${SIDEBAR_DIR}"

              if [ "${SIDEBAR_DIR}" == "." ]
              then
                MARKDOWN_FILE=Home.md
              else
                MARKDOWN_FILE="`basename ${SIDEBAR_DIR}`.md"
              fi

              grep -oP '(?<=^#)#+ .*$' "${MARKDOWN_FILE}" | awk '{
                original_len = length($0)
                sub(/^#+ /,"")
                indent = sprintf("%"(original_len - length($0) - 1)"s","")
                gsub(" ", "\\&nbsp;\\&nbsp;", indent)
                gsub(" ", "", indent)
                link = tolower($0)
                gsub(/[^a-zA-Z0-9 _-]/, "", link)
                gsub(" ", "-", link)
                entry = indent "["$0"](#"link")  "
                print entry
              }' > replace.txt

              sed -i 's/'"${GENERATE_MATCH}"'/cat replace.txt/e' "${SIDEBAR_FILE}"
              rm replace.txt

              popd
            done

  commit-wiki-repo:
    description: Copy files to wiki repo and commit
    parameters:
      commit-user-name:
        type: string
        description: User name with which wiki changes should be commited
        default: CircleCI
      commit-user-email:
        type: string
        description: User email with which wiki changes should be commited
        default: circleci@wiki
      wiki-folder-path:
        type: string
        description: Path to directory containing wiki files
        default: docs
    steps:
      - run:
          name: Clone wiki
          command: git clone ${CIRCLE_REPOSITORY_URL/\.git/.wiki.git} /tmp/wiki
      - run:
          name: Commit changes
          command: |
            export COMMIT_MESSAGE="$(git log --format=%B -n 1 ${CIRCLE_SHA1})"
            cd << parameters.wiki-folder-path >>
            cp -r /tmp/wiki/.git ./
            git config user.email "<< parameters.commit-user-email >>"
            git config user.name "<< parameters.commit-user-name >>"
            git add .
            git commit -m "${COMMIT_MESSAGE}" || changes=none

  push-wiki-repo:
    description: Push changes to wiki repo
    parameters:
      ssh-key-fingerprint:
        type: string
        description: Fingerprint of the SSH key with push access to your repo
      wiki-folder-path:
        type: string
        description: Path to directory containing wiki files
        default: docs
    steps:
      - add_ssh_keys:
          fingerprints:
            - << parameters.ssh-key-fingerprint >>
      - run:
          name: Push to wiki repo
          command: cd << parameters.wiki-folder-path >> && git push

jobs:
  build-and-push:
    description: Populate sidebar files with page header links, commit to wiki repo, and push
    executor: default
    parameters:
      commit-user-name:
        type: string
        description: User name with which wiki changes should be commited
        default: CircleCI
      commit-user-email:
        type: string
        description: User email with which wiki changes should be commited
        default: circleci@wiki
      push-wiki-repo:
        type: boolean
        description: Push to wiki repo after commit
        default: true
      sidebar-placeholder:
        type: string
        description: String in sidebar files to replace with page header links
        default: '{{SIDEBAR_POPULATE}}'
      ssh-key-fingerprint:
        type: string
        description: Fingerprint of the SSH key with push access to your repo
        default: ''
      wiki-folder-path:
        type: string
        description: Path to directory containing wiki files
        default: docs
    steps:
      - checkout
      - populate-sidebars:
          sidebar-placeholder: << parameters.sidebar-placeholder >>
          wiki-folder-path: << parameters.wiki-folder-path >>
      - commit-wiki-repo:
          commit-user-name: << parameters.commit-user-name >>
          commit-user-email: << parameters.commit-user-email >>
          wiki-folder-path: << parameters.wiki-folder-path >>
      - when:
          condition: << parameters.push-wiki-repo >>
          steps:
            - push-wiki-repo:
                ssh-key-fingerprint: << parameters.ssh-key-fingerprint >>
                wiki-folder-path: << parameters.wiki-folder-path >>
